<?php

/**
 * @file
 *
 * - Sample string:
 * @code
 *  <p>This is the first paragraph. It may be HTML.</p>
 *  <hr/>
 *  <p>This is the second paragraph. It may be HTML.</p>
 *  <hr/>
 *  <p>This is the third paragraph. It may be HTML.</p>
 *  <hr/>
 *  <p>This is the forth paragraph. It may be HTML.</p>
 * @endcode
 *
 * - Desired result:
 *  @code
 *    <div class="columns 4-columns">
 *      <div class="column column-1">
 *        <p>This is the first paragraph. It may be HTML.</p>
 *      </div>
 *      <div class="column column-2">
 *        <p>This is the second paragraph. It may be HTML.</p>
 *      </div>
 *      <div class="column column-3">
 *        <p>This is the third paragraph. It may be HTML.</p>
 *      </div>
 *      <div class="column column-4">
 *        <p>This is the forth paragraph. It may be HTML.</p>
 *      </div>
 *    </div>
 *  @endcode
 */

/**
 * Implements hook_filter_info()
 */
function easy_grid_filter_info() {
  $filters['easy_grid'] = array(
    'title' => t('Generate easy gird'),
    'description' => t('Help you to generate some html'),
    'process callback' => 'easy_grid_filter_easy_filter_process',
    'tips callback' => 'easy_grid_filter_easy_filter_tips',
  );

  return $filters;
}

/**
 * Process callback for filter 'easy_grid'
 */
function easy_grid_filter_easy_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  // Normalize the text so that we only deal with <hr>
  $search = array('<hr/>', '<hr />', '<hr >');
  $text = str_replace($search, '<hr>', $text);

  // Split our text into columns and build the proper HTML output
  $output = '';
  $columns = explode('<hr>', $text);
  $count = count($columns);
  if ($count > 1) {
    if ($i == 0) $output .= '<div class="columns '. $count .'-columns">'."\n";
    for ($i = 0; $i < $count; $i++) {
      $output .= '<div class="column column-'. ($i + 1) .'">'."\n";
      $output .= $columns[$i]."\n";
      $output .= '</div>'."\n"; 
    }
    $output .= '</div>'."\n";
  }
  else {
    $output = $text;
  }

  return $output;
}


/**
 * Tips callback for hook_filter_info().
 */
function easy_grid_filter_easy_filter_tips($filter, $format, $long) {


}
